version: '3.8'

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    networks:
      - spring-mysql-net
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker-mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  crudmain-spring:
    image: piyush12singh/spring-mysql-docker-image:01
    container_name: crudmain-spring
    ports:
      - "9002:8080"
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/docker-mysql
      spring.datasource.username: root
      spring.datasource.password: root
      spring.jpa.show-sql: "true"
      spring.jpa.generate-ddl: "true"
      spring.jpa.hibernate.ddl-auto: "update"
    networks:
      - spring-mysql-net
    depends_on:
      - mysqldb

networks:
  spring-mysql-net:
    driver: bridge
