#version: '3.8'
#
#services:
#  mysqldb:
#    image: mysql
#    container_name: mysqldb
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: book
#    networks:
#      - my-sql-net
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 20s
#
#  crudmain-spring:
#    image: piyush12singh/crudmain-spring-docker:latest
#    ports:
#      - "9002:8080"
#    depends_on:
#      mysqldb:
#        condition: service_healthy
#    environment:
#      - spring.application.name=SpringBasicCrud
#      - spring.datasource.url=jdbc:mysql://mysqldb:3306/book
#      - spring.datasource.username=root
#      - spring.datasource.password=root
#      - spring.jpa.show-sql=true
#      - spring.jpa.generate-ddl=true
#      - spring.jpa.hibernate.ddl-auto=update
#    networks:
#      - my-sql-net
#    healthcheck:
#      test: ["CMD", "curl", "--fail", "http://localhost:9002/actuator/health"]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 20s
#
#networks:
#  my-sql-net:
#    external: true



version: '3.8'

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    networks:
      - spring-mysql-net
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker-mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  crudmain-spring:
    image: piyush12singh/spring-mysql-docker-image:01
    container_name: crudmain-spring
    ports:
      - "9002:8080"
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/docker-mysql
      spring.datasource.username: root
      spring.datasource.password: root
      spring.jpa.show-sql: "true"
      spring.jpa.generate-ddl: "true"
      spring.jpa.hibernate.ddl-auto: "update"
    networks:
      - spring-mysql-net
    depends_on:
      - mysqldb

networks:
  spring-mysql-net:
    driver: bridge
